### ISSUE TITLE
Три и более языков

### ISSUE THREAD

**Issue by AlexTemp2019** [klavarog/lang_shift#1]
Есть ли возможность создать слои для других языков (в дополнение к русскому и английскому)?

**Comment by optozorax** [comment]
Нет, я такую возможность не закладывал в эту библиотеку. Для того чтобы это сделать, придётся перепланировать его архитектуру, добавить стандартные раскладки для наиболее часто встречающихся третьих языков: немецкого, украинского итд. А на это у меня нет времени и мотивации (которая бы родилась из спроса, а спрос на это крайне мал).

Тем более что людям с реально тремя-четырьмя языками чаще нужно просто иметь какой-то один слой, например украинско-русский, англо-немецкий, где есть все нужные буквы. Так что моя работа была бы довольно бессмысленной. Тут нужно изобретать совсем другую технологию для многоязычных людей.

А так эта библиотека является просто частным случаем для русскоязычных людей.

**Comment by AlexTemp2019** [comment]
В проделали великолепную работу. В Вашей библиотеке мне очень понравилась идея держать препинаки на одних клавишах независимо от языка. Для моего случая это придётся делать через unicode.
Спасибо.
