### ISSUE TITLE
Странное поведение

### ISSUE THREAD

**Issue by vanarok** [klavarog/lang_shift#2]
Когда я нахожусь на слое с русскими символами и нажимаю модификатор ctrl или alt вместе с русским символом - язык в системе меняется с русского на английский и обратно при повторном нажатии(Почему он не возвращается обратно на язык текущего слоя при отжатии клавиш?). Это ожидаемое поведение?

**Comment by optozorax** [comment]
Зависит от того какой кейкод для CTRL и ALT ты используешь (https://github.com/klavarog/lang_shift/blob/master/include.h#L255-L271).
* Если это `CTRL_0`, то при нажатии CTRL в системе язык не должен переключаться, только слой. При отпускании слой возвращается.
* Если это `CTRL_EN`, то при нажатии CTRL посылается комбинация переключения языка (если сейчас русский) и включение 0 слоя. При отжатии снова посылается комбинация переключения языка (если был русский) и вырубается 0 слой. То есть тут язык должен переключаться на английский только на время нажатия.

Если не хочется использовать ничего из этого, то просто используй `KC_CTRL`.

Для второго случая может быть такое что система не успевает обработать две быстроидущих смены языка. Какая у тебя система и по какому хоткею переключается язык?

**Comment by vanarok** [comment]
Я использую CTRL_0 и ALT_0 в системе Arch linux с хоткеем для смены языка - CAPS.

**Comment by vanarok** [comment]
Попробовал CTRL_EN, он работает корректно, язык меняется при нажатии и возвращается обратно после отжатия(как и слой), в отличии от CTRL_0, который зачем-то меняет язык при использовании с другими кейкодами на слое где у меня русские символы.

**Comment by optozorax** [comment]
>  в отличии от CTRL_0, который зачем-то меняет язык при использовании с другими кейкодами на слое где у меня русские символы.

Вот это я не понял. Скажи пожалуйста:
* У тебя английский на 0 и 1 слое, а русский на 2 и 3 слое?
* В твоём случае какой в данный момент включён язык и слой?
* Ты зажимаешь `CTRL_0`, а потом какие клавиши нажимаешь? Каковы их кейкоды?

**Comment by vanarok** [comment]
* Все так
* Слой с русскими символами и язык русский
* CTRL_0 + ЙЦУКЕН, т.е модификатор и любые русские кейкоды(RU_J, RU_TS, RU_U)

**Comment by optozorax** [comment]
> CTRL_0 + ЙЦУКЕН, т.е модификатор и любые русские кейкоды(RU_J, RU_TS, RU_U)

А как ты можешь нажимать русские кейкоды `RU_J` итд, если у тебя переключается на английский слой, где должны быть английские кейкоды?

**Comment by vanarok** [comment]
> > CTRL_0 + ЙЦУКЕН, т.е модификатор и любые русские кейкоды(RU_J, RU_TS, RU_U)
> 
> А как ты можешь нажимать русские кейкоды `RU_J` итд, если у тебя переключается на английский слой, где должны быть английские кейкоды?

Спасибо что поправил, правильно, я жму английские кейкоды, а не русские

**Comment by optozorax** [comment]
Ааааа, я понял. Значит английские кейкоды автоматически включают английский язык на время своего нажатия. Получается `CTRL_0` не работающая штука по определению. Это баг, постараюсь исправить в ближайшее время.

**Comment by ghost** [comment]
You closed issue for nothing. Bug still exists.
